// Generated by CoffeeScript 1.8.0
(function() {
  var domain,
    __slice = [].slice;

  domain = require('domain');

  $.next = process.nextTick;

  process.on('uncaughtException', function(err) {
    $.info('fatal', err);
    return $.log(err.stack);
  });

  $["try"] = function() {
    var o, p;
    p = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
    o = {
      _domain: domain.create(),
      "try": function(fn) {
        $.next(function() {
          return o._domain.run(fn);
        });
        return o;
      },
      "catch": function(fn) {
        o._catch = fn;
        return o;
      }
    };
    o._domain.on('error', function(err) {
      $.info('error', err);
      return typeof o._catch === "function" ? o._catch(err) : void 0;
    });
    if (($.type(p[0])) === 'function') {
      o["try"](p[0]);
    }
    if (($.type(p[1])) === 'function') {
      o["catch"](p[1]);
    }
    return o;
  };

}).call(this);
