// Generated by CoffeeScript 1.8.0
(function() {
  var __slice = [].slice;

  $.Deferred = (function() {
    function Deferred() {}

    Deferred.prototype.done = function(callback) {
      this.list || (this.list = {
        done: $.Callbacks(),
        fail: $.Callbacks()
      });
      this.list.done.add(callback);
      return this;
    };

    Deferred.prototype.fail = function(callback) {
      this.list || (this.list = {
        done: $.Callbacks(),
        fail: $.Callbacks()
      });
      this.list.fail.add(callback);
      return this;
    };

    Deferred.prototype.resolve = function() {
      var p, _ref;
      p = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
      if (this.list) {
        (_ref = this.list.done).fire.apply(_ref, p);
      }
      return this;
    };

    Deferred.prototype.reject = function() {
      var p, _ref;
      p = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
      if (this.list) {
        (_ref = this.list.fail).fire.apply(_ref, p);
      }
      return this;
    };

    return Deferred;

  })();

}).call(this);
